<?php

return [
    'moroccan_cities' => [
        ['value' => 'Casablanca', 'label' => 'Casablanca'],
        ['value' => 'Rabat', 'label' => 'Rabat'],
        ['value' => 'Sale', 'label' => 'Salé'],
        ['value' => 'Tanger', 'label' => 'Tanger'],
        ['value' => 'Marrakech', 'label' => 'Marrakech'],
        ['value' => 'Fes', 'label' => 'Fès'],
        ['value' => 'Meknes', 'label' => 'Meknès'],
        ['value' => 'Agadir', 'label' => 'Agadir'],
        ['value' => 'Oujda', 'label' => 'Oujda'],
        ['value' => 'Kenitra', 'label' => 'Kénitra'],
        ['value' => 'Tetouan', 'label' => 'Tétouan'],
        ['value' => 'El Jadida', 'label' => 'El Jadida'],
        ['value' => 'Safi', 'label' => 'Safi'],
        ['value' => 'Mohammedia', 'label' => 'Mohammedia'],
        ['value' => 'Beni Mellal', 'label' => 'Beni Mellal'],
        ['value' => 'Nador', 'label' => 'Nador'],
        ['value' => 'Khouribga', 'label' => 'Khouribga'],
        ['value' => 'Settat', 'label' => 'Settat'],
        ['value' => 'Larache', 'label' => 'Larache'],
        ['value' => 'Ksar El Kebir', 'label' => 'Ksar El Kebir'],
        ['value' => 'Taza', 'label' => 'Taza'],
        ['value' => 'Errachidia', 'label' => 'Errachidia'],
        ['value' => 'Ouarzazate', 'label' => 'Ouarzazate'],
        ['value' => 'Laayoune', 'label' => 'Laâyoune'],
        ['value' => 'Dakhla', 'label' => 'Dakhla'],
        ['value' => 'Guelmim', 'label' => 'Guelmim'],
        ['value' => 'Essaouira', 'label' => 'Essaouira'],
        ['value' => 'Taroudant', 'label' => 'Taroudant'],
        ['value' => 'Berrechid', 'label' => 'Berrechid'],
        ['value' => 'Temara', 'label' => 'Temara'],
    ],
];
